poging tot ShowGamesByUser endpoint, lopen vast bij db probleem
Na drop cascade van tabel games is hele db opnieuw ververst.
Ik had in application.properties

spring.jpa.hibernate.ddl-auto=update

gewijzigd naar

spring.jpa.hibernate.ddl-auto=auto

Nu eerst uitzoeken hoe ik de boel waar aan de praat krijg,

FOUTMELDING:
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.amount" is null
	at nl.hu.bep2.casino.chips.domain.Chips.deposit(Chips.java:61) ~[classes/:na]